/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigProvider: typeof import('./src/components/ConfigProvider.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    PostBlog: typeof import('./src/views/PostBlog.vue')['default']
    Poster: typeof import('./src/components/Poster.vue')['default']
    PosterTest: typeof import('./src/components/poster-test.vue')['default']
    Profile: typeof import('./src/views/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserSettings: typeof import('./src/views/UserSettings.vue')['default']
  }
}
